server:
  port: 8085
  
spring:
  data:
    mongodb:
      uri:  mongodb://localhost:27017/HMS-BOOKINGS-DB
      auto-index-creation: true
      
  application:
    name: BOOKINGS-SERVICE
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    